version: "3"
services:
  s3:
    image: "minio/minio"
    restart: "no"
    environment:
      - MINIO_ACCESS_KEY=s3accesskey
      - MINIO_SECRET_KEY=s3secretkey
    expose:
      - "9000"
    ports:
      - "9000:9000"
    entrypoint: ["minio", "server", "/data"]

  db:
    image: "postgres"
    restart: "no"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=changeme
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - .:/docker-entrypoint-initdb.d:delegated

  app:
    build: .
    restart: "no"
    environment:
      - DATABASE_NAME=db
      - DATABASB_USERNAME=username
      - DATABASB_PASSWORD=changeme
      - S3_ENDPOINT="localhost:9000"
      - S3_REGION="us-east-1"
      - S3_BUCKET="filebin"
      - S3_ACCESS_KEY=s3accesskey
      - S3_SECRET_KEY=s3secretkey
    expose:
      - "8888"
    ports:
      - "8888:8888"
    volumes:
      - .:/app:delegated
    depends_on:
      - db
      - s3
    entrypoint: ["make"]

  #varnish:
  #  image: "varnish:stable"
  #  restart: "no"
  #  expose:
  #    - "6081"
  #  ports:
  #    - "6081:80"
  #  volumes:
  #    - ./etc/varnish:/etc/varnish:delegated
  #  depends_on:
  #    - app
