version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up --abort-on-container-exit
