version: 2.1
jobs:
  build:
    machine:
      image: true
    steps:
      - checkout
      - run: docker-compose up --abort-on-container-exit
      - store_artifacts:
          path: artifacts/
          destination: /
      - store_test_results:
          path: tests/
workflows:
  version: 2
  build:
    jobs:
      - build
