version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
      - image: circleci/postgres:12.0-alpine
        environment:
          - POSTGRES_DB=db
          - POSTGRES_USER=username
          - POSTGRES_PASSWORD=changeme
    steps:
      - checkout
      - run: echo "127.0.0.1 db" > /etc/hosts
      - run: go test dbl/* -mod=vendor -v -cover
