version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker-compose up --abort-on-container-exit
      - codecov/upload:
          file: coverage.out
      - store_artifacts:
          path: artifacts/
          destination: /
      - store_test_results:
          path: tests/
workflows:
  version: 2
  build:
    jobs:
      - build
