version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker
      - run: docker-compose up --abort-on-container-exit
