version: 2
jobs:
  build:
    machine:
      image: true
    steps:
      - checkout
      - run: docker-compose up --abort-on-container-exit
      - store_artifacts:
          path: out/
          destination: /
workflows:
  version: 2
  build:
    jobs:
      - build
